// Test generated by RoostGPT for test petclinic-trigger using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.mock;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.model.Pet;
import org.springframework.samples.petclinic.model.PetType;

public class Pet_getType_5e69a8c7da_Test {

    private Pet pet;

    @BeforeEach
    public void setup() {
        pet = new Pet();
    }

    @Test
    public void testGetType_whenTypeIsSet() {
        PetType type = mock(PetType.class);
        pet.setType(type);

        PetType result = pet.getType();

        assertEquals(type, result, "Expected and actual PetType should match");
    }

    @Test
    public void testGetType_whenTypeIsNotSet() {
        PetType result = pet.getType();

        assertEquals(null, result, "Expected PetType should be null when not set");
    }
}
