// Test generated by RoostGPT for test petclinic-trigger using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.visit.Visit;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.mock;

public class Pet_addVisit_99c71f5c31_Test {

    private Pet pet;
    private Visit visit;

    @BeforeEach
    public void setup() {
        pet = new Pet();
        visit = mock(Visit.class); // Mocking the Visit class
    }

    @Test
    public void testAddVisitSuccess() {
        pet.addVisit(visit);
        assertTrue(pet.getVisits().contains(visit), "Visit should be added successfully");
    }

    @Test
    public void testAddVisitFailure() {
        Visit anotherVisit = mock(Visit.class);
        pet.addVisit(anotherVisit);
        assertTrue(!pet.getVisits().contains(visit), "Visit should not be added as it was not the visit intended to be added");
    }
}
