// Test generated by RoostGPT for test petclinic-trigger using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.ui.ModelMap;
import org.springframework.validation.BindingResult;
import org.springframework.validation.FieldError;

import java.time.LocalDate;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.*;

public class PetController_processUpdateForm_e1332752ad_Test {

    @InjectMocks
    private PetController petController;

    @Mock
    private Owner owner;

    @Mock
    private Pet pet;

    @Mock
    private BindingResult result;

    @Mock
    private ModelMap model;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testProcessUpdateForm_duplicatePetName() {
        when(pet.getName()).thenReturn("Fido");
        when(owner.getPet("fido", false)).thenReturn(new Pet());
        when(pet.getId()).thenReturn(1);
        when(owner.getPet("fido", false).getId()).thenReturn(2);

        String view = petController.processUpdateForm(pet, result, owner, model);

        verify(result).rejectValue("name", "duplicate", "already exists");
        assertEquals("pets/createOrUpdatePetForm", view);
    }

    @Test
    public void testProcessUpdateForm_futureBirthDate() {
        when(pet.getBirthDate()).thenReturn(LocalDate.now().plusDays(1));

        String view = petController.processUpdateForm(pet, result, owner, model);

        verify(result).rejectValue("birthDate", "typeMismatch.birthDate");
        assertEquals("pets/createOrUpdatePetForm", view);
    }

    @Test
    public void testProcessUpdateForm_successfulUpdate() {
        when(pet.getName()).thenReturn("Fido");
        when(owner.getPet("fido", false)).thenReturn(null);
        when(pet.getBirthDate()).thenReturn(LocalDate.now().minusYears(1));
        when(result.hasErrors()).thenReturn(false);

        String view = petController.processUpdateForm(pet, result, owner, model);

        verify(owner).addPet(pet);
        assertEquals("redirect:/owners/{ownerId}", view);
    }
}
