// Test generated by RoostGPT for test petclinic-trigger using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;

import static org.junit.jupiter.api.Assertions.assertEquals;

@SpringBootTest
public class BaseEntity_setId_58357d9c06_Test {

    private BaseEntity baseEntity;

    @BeforeEach
    public void setUp() {
        baseEntity = new BaseEntity();
    }

    @Test
    public void testSetId_ValidId() {
        Integer validId = 10;
        baseEntity.setId(validId);
        assertEquals(validId, baseEntity.getId(), "The ID should be set correctly.");
    }

    @Test
    public void testSetId_NullId() {
        baseEntity.setId(null);
        assertEquals(null, baseEntity.getId(), "The ID should be null.");
    }
}
